apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: read-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: read-service-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50