# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-super-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: voucher-hub-service
                port:
                  number: 5173
          - path: /read/?(.*)
            pathType: Prefix
            backend:
              service:
                name: read-service-service
                port:
                  number: 8080
          - path: /write/?(.*)
            pathType: Prefix
            backend:
              service:
                name: write-service-service
                port:
                  number: 1234
          

     