apiVersion: apps/v1
kind: Deployment
metadata:
  name: read-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readservice
  template:
    metadata:
      labels:
        app: readservice
    spec:
      containers:
        - name: readservice
          image: read-service
          imagePullPolicy: Never # Uses Minikubes Docker image repo (minikube only)
          ports:
            - containerPort: 8080
          resources: # Define resource requests here
            requests:
              cpu: "100m" # Set your desired CPU request here

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: read-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: read-service-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
